[tool.poetry]
name = "pythonweb-hw6"
version = "0.1.0"
description = ""
authors = ["dmytrot <dmytrot0208@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
faker = "^23.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
